# Conclusion

In this report, we analyze the spread and prevention of COVID-19. By observing the global reported cases and deaths by time and space, we explored the overall spreading pattern of the pandemic. As vaccination effectively prevents the spreading of the virus, we also looked at the vaccination rate data. And for more detailed patterns, we focused only on the US vaccination.

We found that the reported cases kept growing ever since the outbreak of the pandemic in 2019, but began slowing down in December 2020 with the growth of immunity and the promotion of vaccines. The most significant peak of reported cases appeared in January 2022 with the spread of the Omicron variant. However, the reported deaths did not increase that much in the meantime, from which we could conclude that Omicron spreads more easily than earlier variants, but causes less severe illness and death in general.

By analyzing the global distribution of cases, deaths, and vaccination rates, we found that the bordering countries show similar patterns,  while the countries with strict COVID-19 policies show lower rates compared to surrounding countries, for instance, China. We observed higher death rates in the US compared to European countries with similar or even higher infection rates. We doubt that different methods of counting deaths may have influenced the comparison across regions, leading to more complex questions which may need further information and insights for the explanation.

For the vaccination data, we first observed that the US fully vaccinated rate is 68%, between the median and the third quantile of the global rate 33.7% of the US population has taken the booster, but there are still 20.3% of the population who have not taken any vaccine. We also noticed that the vaccination rate grows with age. Specifically, people aged over 65 have the highest fully vaccinated rate of 88.6% and a vaccinated rate of 95%. 

By comparing the outcomes across the United States before and after the initiation of vaccination programs, we evaluated the impact of vaccination on the COVID-19 pandemic. COVID-19-related deaths declined steeply during February - April 2022 and remained through August 2022 compared to rates observed during June 2021 – February 2022. As vaccination rates increase in the United States, vaccines continued to be effective in reducing COVID-19–related mortality.

It has been two years since the first COVID-19 vaccine was given to a patient in the United States. The US average fully vaccinated rate is 68.9% now, and the impact of the vaccination program is more remarkable given the challenges posed by the multiple variants that have arisen. The Delta variant has substantially postponed the predicted herd immunity date, through a combination of reduced vaccine effectiveness, and increased infection and death rates. The Omicron variants have been particularly immune-evasive and caused the largest wave of infections during the pandemic. However, vaccination has significantly slowed the growth of total COVID-19 cases and provides broader protection against death.
