# Proposal

## Research topic
The research focuses on the data of COVID-19. We aim to explore the worldwide spread trend of the disease as well as detailed patterns in specific countries. The questions we are most curious about include: What is the overall trend of the incidence across the world from 2019 to 2022? How much does vaccination prevent the spread? How does special public health and social measures influence the incidence and are there any side-effects?

The context of the research is organised as the following. In the first part of the analysis, we explore the global COVID-19 cases and deaths, with time ranging from 2019 to 2022. We hope to present the overall pattern of the spread in different time and spaces. The second part of the research features the the introduction and influence of the vaccination. We analyze only vaccination data in the US to reveal more detailed information. In the last part of the research, we look at the effects of special public health measures in preventing the epidemic, as well as their potential influence in the society. This part uses data from China, where strict policies, like restriction on gatherings or adapting and closing offices have taken place.

## Data availability

We will use data from the WHO coronavirus (COVID-19) dashboard, U.S. COVID-19 Data from JHU and data dashboard website of National Bureau of Statistics of China.

### The WHO coronavirus (COVID-19) dashboard 

The dashboard data present official daily counts of COVID-19 cases, deaths and vaccine utilisation reported by countries, territories and areas.Links:<https://covid19.who.int/data>

#### Data source

**Case and death count data:** WHO collected the numbers of confirmed COVID-19 cases and deaths through official communications, complemented by monitoring the official ministries of health websites and social media accounts. Since 22 March 2020, global data are compiled through WHO region-specific dashboards, and/or aggregate count data reported to WHO headquarters daily.

**Vaccine data:** these data are pooled from numerous sources, including direct reports from Member States, WHO review of publicly available official data, or data collated and published by third-party sites.

#### Data format

Data can be downloaded in comma-separated values (CSV) files. They can be imported by R read.csv() function.

#### Frequency of updates

Cases and deaths are updated on a daily basis except weekends. Vaccine data are updated on a weekly basis. WHO continues to encourage all users to prioritize weekly counts and long-term trends (over several weeks) as a more reliable measure of COVID-19 epidemiological activity.


### U.S. COVID-19 Data - JHU

#### Description

The cases and deaths data provides cases and deaths dating back to the beginning of the pandemic in January 2020. Link: <https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports_us>

The vaccination data provides the vaccination efforts across the United States. Link: <https://github.com/govex/COVID-19/tree/master/data_tables/vaccine_data/us_data>

#### Data source

Cases and deaths data: the data is sourced from governments, national and subnational agencies across the country - a full list of data sources is published on [Johns Hopkins's GitHub site](https://github.com/CSSEGISandData/COVID-19). COVID-19 data were collected by states and consolidated by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University.

Vaccination data: the data is sourced from the U.S. Centers for Disease Control and Prevention (CDC). Federal agency data are included as part of jurisdiction, state, or territory aggregate metrics. To avoid duplicate counts, the agency data will not be combined with other data. National and jurisdictional metrics reported to CDC include vaccination data distribution to and administered in the jurisdiction partner clinics, retail pharmacies, and federal partners and programs.

#### Data format

The data can be downloaded as csv file. We will combine the data files in R for data analysis.

#### Frequency of updates

Covid cases and deaths data are updated once per day between 04:45 and 05:15 GMT, with the most recent official numbers up to the previous day. Vaccination data are updated once a week, with data up to the previous day. Data from previous days will be updated as vaccination records are processed.

#### Delays in death reports

The number of deaths reported on a given day does not necessarily reflect the actual number of COVID-19 deaths on that day, or in the previous 24 hours. This is due to lags and delays in reporting.

The delay in reporting can be on the order of days and sometimes as long as a week or more. This means the number of deaths *reported* on a given day is not reflective of the actual number of deaths that occurred on that day.

### National Bureau of Statistics of China

We can find the total mortality rate of China at a yearly basis on the national data website of National Bureau of Statistics of China.Links:<https://data.stats.gov.cn/easyquery.htm?cn=C01>

#### Data source
 
National Bureau of Statistics of China collects and calculates the data based on sample survey.
 
#### Data format
 
 The data can be downloaded in CSV files. They can be imported by R read.csv() function.
 
#### Frequency of updates
 
 The total mortality rates are updated on an annual basis.


