---
title: "Codes & Graphs_lwp"
author: "Weipeng Li"
date: "2022-11-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(scales)
library(lubridate)
library(glue)
library(ggridges)
library(colorspace)
```

## Worldwide cases/deaths of covid-19 - time series

```{r}
# data preprocessing
# only keep the new reported data
who_daily <- read.csv("WHO-COVID-19-global-data.csv")
world_daily <- who_daily %>%
  group_by(Date_reported) %>%
  mutate(world_new_cases = sum(New_cases)) %>%
  #mutate(world_cumulative_cases = sum(Cumulative_cases)) %>%
  mutate(world_new_deaths = sum(New_deaths)) %>%
  #mutate(world_cumulative_deaths = sum(Cumulative_deaths)) %>%
  select(c(Date_reported, world_new_cases, world_new_deaths)) %>%
  distinct()  %>%
  mutate(Date_reported = as.Date(Date_reported))
summary(world_daily)

# convert to long format
world_daily_long <- pivot_longer(world_daily,col=!Date_reported) 
world_daily_long
```
```{r}
world_weekly <- world_daily %>%
  mutate(week = as.numeric(floor((Date_reported-as.Date('2020-01-03'))/7))) %>%
  group_by(week) %>%
  mutate(weekly_new_cases = sum(world_new_cases)) %>%
  mutate(weekly_new_deaths = sum(world_new_deaths)) %>%
  mutate(date_reported = as.Date(as.Date('2020-01-03')+week*7)) %>%
  select(date_reported,weekly_new_cases,weekly_new_deaths,week) %>%
  ungroup() %>%
  distinct()
world_weekly
```



```{r}
# new cases by day
ggplot(world_daily,aes(Date_reported,world_new_cases))+
  geom_area(color='red',fill='pink',alpha=0.5)+
  scale_x_date(breaks = function(x) seq.Date(from = min(x), to = max(x), by = "4 months"),
               labels = function(x) paste(lubridate::year(x),'-',lubridate::month(x), sep=''))+
  xlab('Date Reported')+
  ylab('New Cases')+
  ggtitle('Daily New Reported Cases')+
  theme_light()
```
```{r}
ggplot(world_weekly, aes(date_reported,weekly_new_cases))+
  geom_area(color='red',fill='pink',alpha=0.5)+
  scale_x_date(breaks = function(x) seq.Date(from = min(x), to = max(x), by = "4 months"),
               labels = function(x) paste(lubridate::year(x),'-',lubridate::month(x), sep=''))+
  xlab('Date Reported')+
  ylab('New Cases')+
  ggtitle('Weekly New Reported Cases')+
  theme_light()
```

```{r}
# new deaths by day
ggplot(world_daily, aes(Date_reported,world_new_deaths))+
  geom_area(color='black',fill='grey',alpha=0.5)+
  scale_x_date(breaks = function(x) seq.Date(from = min(x), to = max(x), by = "4 months"),
               labels = function(x) paste(lubridate::year(x),'-',lubridate::month(x), sep=''))+
  xlab('Date Reported')+
  ylab('Deaths')+
  ggtitle('Daily Deaths')+
  theme_light()
```
```{r}
ggplot(world_weekly, aes(date_reported,weekly_new_deaths))+
  geom_area(color='black',fill='grey',alpha=0.5)+
  scale_x_date(breaks = function(x) seq.Date(from = min(x), to = max(x), by = "4 months"),
               labels = function(x) paste(lubridate::year(x),'-',lubridate::month(x), sep=''))+
  xlab('Date Reported')+
  ylab('Deaths')+
  ggtitle('Weekly Deaths')+
  theme_light()
```

# ```{r}
# # new cases of 2022.11
# world_daily %>%
#   filter(Date_reported >= '2022-10-31' & Date_reported <='2022-11-13') %>%
#   ggplot(aes(Date_reported,world_new_cases)) +
#   scale_x_date(breaks = function(x) seq.Date(from = min(x), to = max(x), by = "1 day"),
#                labels = function(x) paste(lubridate::month(x),'-',lubridate::day(x), sep=''))+
#   xlab('Date Reported')+
#   geom_line() +
#   xlab('Date Reported') +
#   ylab('New Cases') +
#   theme_grey(14)
#```

# ```{r}
# # new deaths by day after Nov 2021
# world_daily %>%
#   filter(Date_reported >= '2022-10-31' & Date_reported <='2022-11-13') %>%
#   ggplot(aes(Date_reported,world_new_deaths)) +
#   geom_line() +
#   scale_x_date(breaks = function(x) seq.Date(from = min(x), to = max(x), by = "1 day"),
#                labels = function(x) paste(lubridate::month(x),'-',lubridate::day(x), sep=''))+
#   xlab('Date Reported') +
#   ylab('New Deaths') +
#   theme_grey(14)
# ```

## Worldwide Vaccintaion Data

```{r}
# data preprocessing
world_vac_df <- read.csv('vaccination-data.csv')
#summary(world_vac_df)
world_vac <- world_vac_df %>%
  select(COUNTRY,PERSONS_FULLY_VACCINATED_PER100) %>%
  rename(country=COUNTRY, fully_vaccinated_rate = PERSONS_FULLY_VACCINATED_PER100)


# check for missing values and outliers
na_index <- c(which(is.na(world_vac$fully_vaccinated_rate)),which(world_vac$fully_vaccinated_rate<=0))
outlier_index <- which(world_vac$fully_vaccinated_rate>100)
world_vac[c(na_index,outlier_index),]
world_vac <- world_vac[-c(na_index,outlier_index),]
world_vac
```

```{r}
# Set panels for visualization
world_vac_panel <- world_vac %>%
  mutate(Panel=cut(fully_vaccinated_rate,10,breaks=c(0,12.5,25,37.5,50,62.5,75,87.5,100),
         labels=c('<12.5%','12.5%-25.0%','25.0%-37.5%','37.5%-50.0%',
                  '50.0%-62.5%','62.5%-75.0%','75.0%-87.5%','>87.5%'))) %>%
  mutate(Panel=fct_rev(Panel))
world_vac_panel
```

```{r}
world_vac_panel %>%
  filter(Panel %in% c('50.0%-62.5%','62.5%-75.0%','75.0%-87.5%','>87.5%')) %>%
  ggplot(aes(fully_vaccinated_rate, y = reorder(country, fully_vaccinated_rate))) +
  geom_point(size=0.6) +
  facet_wrap(~Panel, ncol = 2, scales = "free") +
  ggtitle('Vaccination Rate by Country') +
  xlab('') +
  ylab('')+
  theme(axis.text.y=element_text(size=4))+
  theme_light()
```
```{r}
world_vac_panel %>%
  filter(Panel %in% c('<12.5%','12.5%-25.0%','25.0%-37.5%','37.5%-50.0%')) %>%
  ggplot(aes(fully_vaccinated_rate, y = reorder(country, fully_vaccinated_rate))) +
  geom_point(size=0.6) +
  facet_wrap(~Panel, ncol = 2, scales = "free") +
  #ggtitle('Vaccination Rate by Country') +
  xlab('Vaccination Rate') +
  ylab('')+
  theme(axis.text.y=element_text(size=4))+
  theme_light()
```
# ```{r}
# world_vac_cleveland <- world_vac %>%
#   mutate(color='black')
# 
# us_vac_for_density <- world_vac %>%
#   filter(country=='United States of America') %>%
#   mutate(color='red')
# 
# my_labels <- glue_data(
#   world_vac,
#   "<span style='color: {if_else(country=='United States of America', 'red', 'blue')}'>{country}</span>"
#   )
# names(my_labels) <- world_vac$country
# 
# world_vac %>%
#   filter(fully_vaccinated_rate > 60) %>%
#   ggplot(aes(fully_vaccinated_rate,
#                             fct_reorder(country,fully_vaccinated_rate))) +
#   geom_point(size=0.6) +
#   geom_point(data=us_vac_cleveland, aes(fully_vaccinated_rate,country),
#              color='red',size=0.6)+
#   ggtitle('Vaccination Rate by Country') +
#   xlab('Vaccination Rate') +
#   ylab('')+
#   theme(axis.text.y=element_text(size=4)) +
#   scale_x_discrete(labels=my_labels)
# ```


```{r}
ggplot(world_vac, aes(fully_vaccinated_rate)) +
  geom_density(fill = "pink",alpha = .3) +
  geom_vline(aes(xintercept=fully_vaccinated_rate),
             data=us_vac_for_density,color='red',linetype='dotted')+
  geom_text(aes(x=82, label="\nUnited States: 67.989", y=0.012), color="red")+
  ggtitle("Global Fully Vaccinated Rate") +
  xlab('Fully Vaccinated Rate')
```

```{r}
ggplot(world_vac, aes(x=fully_vaccinated_rate)) +
  geom_boxplot()+
  geom_segment(x=67.789,xend=67.789,y=-0.37,yend=0.37,color='red',linetype='dotted')+
  geom_text(aes(x=73, label="\nUnited States: 67.989", y=0.3), color="red",size=3)+
  ggtitle('US Fully Vaccinated Rate Comparing to Global Data') +
  xlab('Fully Vaccinated Rate')+
  ylab('')+
  theme(legend.title=element_blank())+
  coord_flip()+
  theme_light()
```

# ```{r}
# world_vac_box <- world_vac_df %>%
#   select(COUNTRY,WHO_REGION,PERSONS_FULLY_VACCINATED_PER100) %>%
#   rename(country=COUNTRY, region=WHO_REGION, fully_vaccinated_rate = PERSONS_FULLY_VACCINATED_PER100) %>%
#   filter(region!='OTHER')
#
# ggplot(world_vac_box,
#        aes(x=reorder(region, -fully_vaccinated_rate, median),
#            y=fully_vaccinated_rate))+
#   geom_boxplot()+
#   geom_segment(x=2.62,xend=3.38,y=67.789,yend=67.789,colour="red",linetype='dotted')+
#   #geom_text(aes(x=2, label="\nUnited States: 67.989", y=67), color="red",size=3)+
#   ggtitle('Fully Vaccinated Rate by Continents')+
#   xlab('Continents') +
#   ylab('Fully Vaccinated Rate')
# ```


## Vaccination in American Population

```{r}
us_vac <- world_vac_df %>%
  filter(COUNTRY=='United States of America') %>%
  select(PERSONS_VACCINATED_1PLUS_DOSE_PER100,
         PERSONS_FULLY_VACCINATED_PER100,
         PERSONS_BOOSTER_ADD_DOSE_PER100) %>%
  rename(vaccinated=PERSONS_VACCINATED_1PLUS_DOSE_PER100,
         fully_vaccinated=PERSONS_FULLY_VACCINATED_PER100,
         boosted=PERSONS_BOOSTER_ADD_DOSE_PER100) %>%
  mutate(not_vaccinated=100-vaccinated) %>%
  mutate(vaccinated=vaccinated-fully_vaccinated) %>%
  mutate(fully_vaccinated=fully_vaccinated-boosted) %>%
  mutate(country='United States of America') %>%
  pivot_longer(!country)
us_vac
```

# ```{r}
# ggplot(us_vac, aes(fct_rev(fct_relevel(name,'not_vaccinated',after=Inf)),value)) +
#   geom_col() +
#   xlab('Vaccination State')+
#   ylab('Percent') +
#   ggtitle('Vaccination State in US Population') +
#   geom_text(aes(label=value), position=position_dodge(width=0.9), vjust=-0.25)
# ```

```{r}
us_vac$name <- factor(us_vac$name, levels=c('boosted','fully_vaccinated','vaccinated','not_vaccinated'))
us_vac$country <- rep('',4)


ggplot(us_vac, aes(country,value,fill=fct_rev(name)))+
  geom_col()+
  geom_text(aes(x=1, label="33.7%", y=26), color="black",size=4)+
  geom_text(aes(x=1, label="34.3%", y=60), color="black",size=4)+
  geom_text(aes(x=1, label="11.7%", y=74), color="black",size=4)+
  geom_text(aes(x=1, label="20.3%", y=94), color="black",size=4)+
  xlab('')+
  ylab('Proportion')+
  ggtitle('Vaccination State of US Population')+
  scale_fill_discrete_sequential(palette = "Terrain2")+
  theme(plot.margin=unit(rep(2,8),'cm'))+
  theme_light()+
  theme(legend.title=element_blank())+
  coord_flip()



```


## Vaccination Rate by Ages


```{r}
# data preprocessing
vac_age_df <- read.csv('COVID-19_Vaccination_and_Case_Trends_by_Age_Group__United_States.csv')
vac_age <- vac_age_df %>%
  select(Date.Administered,AgeGroupVacc,Series_Complete_Pop_pct_agegroup,
         X7.day_avg_group_cases_per_100k,Administered_Dose1_pct_agegroup) %>%
  rename(date=Date.Administered,age=AgeGroupVacc,
         fully_vaccinated_rate=Series_Complete_Pop_pct_agegroup,
         vaccinated_rate=Administered_Dose1_pct_agegroup,
         case_rate=X7.day_avg_group_cases_per_100k)%>%
  filter(date==max(date)) %>%
  mutate(vaccinated_rate=percent(vaccinated_rate)) %>%
  mutate(fully_vaccinated_rate=percent(fully_vaccinated_rate)) %>%
  mutate(case_rate=percent(case_rate/100000)) %>%
  filter(age %in% c('5 - 11 Years','12 - 17 Years','18 - 24 Years','25 - 49 Years',
                    '50 - 64 Years', '65+ Years'))

vac_age_long <- pivot_longer(vac_age[,c(2,3,5)],cols=!age)
vac_age_long
# case_age <- vac_age_df %>%
#   select(Date.Administered,AgeGroupVacc,X7.day_avg_group_cases_per_100k) %>%
#   rename(date=Date.Administered, age=AgeGroupVacc, week_case_rate=X7.day_avg_group_cases_per_100k) %>%
#   group_by(age) %>%
#   mutate(avg_case_rate=mean(week_case_rate)/1000) %>%
#   filter(age %in% c('5 - 11 Years','12 - 17 Years','18 - 24 Years','25 - 49 Years',
#                     '50 - 64 Years', '65+ Years')) %>%
#   filter(date==max(date))

```

```{r}
ggplot(vac_age_long, aes(fct_relevel(age,'5 - 11 Years'),value,fill=name)) +
  geom_col(position=position_dodge(),alpha=0.6) +
  #geom_line(data=vac_age,aes(fct_relevel(age,'5 - 11 Years'),case_rate))+
  geom_text(aes(label=value), position=position_dodge(width=0.9), vjust=-0.3,size=3)+
  xlab('Ages')+
  ylab('Vaccinated Rate') +
  ggtitle('Vaccinatied and Reported Case Rate by Age')+
  scale_fill_discrete(name='')+ 
  #scale_fill_discrete_sequential(palette = "Terrain2")+
  theme_light()
```



<!-- ```{r} -->
<!-- # world_vac_filter <- world_vac %>% -->
<!-- #   add_row(country='Others',fully_vaccinated_rate=mean(world_vac$fully_vaccinated_rate[world_vac$fully_vaccinated_rate < 80], na.rm=TRUE)) %>% -->
<!-- #   filter(fully_vaccinated_rate > 80 | country=='Others') -->
<!-- # ggplot(world_vac_filter, aes(x=fully_vaccinated_rate, y=fct_reorder(country,fully_vaccinated_rate)))+ -->
<!-- #   geom_point()+ -->
<!-- #   xlab('Fully Vaccinated Rate')+ -->
<!-- #   ylab('')+ -->
<!-- #   ggtitle('Fully Vaccinated Rate for Countries') -->
<!-- ``` -->





